	//----Message types----

	// Authentication and connection monitoring
	const LOGON_REQUEST = 1;
	const LOGON_RESPONSE = 2;
	const HEARTBEAT = 3;
	const LOGOFF = 5;
	const ENCODING_REQUEST = 6;
	const ENCODING_RESPONSE = 7;

	// Market data
	const MARKET_DATA_REQUEST = 101;
	const MARKET_DATA_REJECT = 103;
	const MARKET_DATA_SNAPSHOT = 104;
	const MARKET_DATA_SNAPSHOT_INT = 125;

	const MARKET_DATA_UPDATE_TRADE = 107;
	const MARKET_DATA_UPDATE_TRADE_COMPACT = 112;
	const MARKET_DATA_UPDATE_TRADE_INT = 126;
	const MARKET_DATA_UPDATE_LAST_TRADE_SNAPSHOT = 134;
	const MARKET_DATA_UPDATE_TRADE_WITH_UNBUNDLED_INDICATOR = 137;

	const MARKET_DATA_UPDATE_BID_ASK = 108;
	const MARKET_DATA_UPDATE_BID_ASK_COMPACT = 117;
	const MARKET_DATA_UPDATE_BID_ASK_INT = 127;

	const MARKET_DATA_UPDATE_SESSION_OPEN = 120;
	const MARKET_DATA_UPDATE_SESSION_OPEN_INT = 128;
	const MARKET_DATA_UPDATE_SESSION_HIGH = 114;
	const MARKET_DATA_UPDATE_SESSION_HIGH_INT = 129;
	const MARKET_DATA_UPDATE_SESSION_LOW = 115;
	const MARKET_DATA_UPDATE_SESSION_LOW_INT = 130;
	const MARKET_DATA_UPDATE_SESSION_VOLUME = 113;
	const MARKET_DATA_UPDATE_OPEN_INTEREST = 124;
	const MARKET_DATA_UPDATE_SESSION_SETTLEMENT = 119;
	const MARKET_DATA_UPDATE_SESSION_SETTLEMENT_INT = 131;
	const MARKET_DATA_UPDATE_SESSION_NUM_TRADES = 135;
	const MARKET_DATA_UPDATE_TRADING_SESSION_DATE = 136;

	const MARKET_DEPTH_REQUEST = 102;
	const MARKET_DEPTH_REJECT = 121;
	const MARKET_DEPTH_SNAPSHOT_LEVEL = 122;
	const MARKET_DEPTH_SNAPSHOT_LEVEL_INT = 132;
	const MARKET_DEPTH_UPDATE_LEVEL = 106;
	const MARKET_DEPTH_UPDATE_LEVEL_COMPACT = 118;
	const MARKET_DEPTH_UPDATE_LEVEL_INT = 133;
	const MARKET_DEPTH_FULL_UPDATE_10 = 123;
	const MARKET_DEPTH_FULL_UPDATE_20 = 105;

	const MARKET_DATA_FEED_STATUS = 100;
	const MARKET_DATA_FEED_SYMBOL_STATUS = 116;

	// Order entry and modification
	const SUBMIT_NEW_SINGLE_ORDER = 208;
	const SUBMIT_NEW_SINGLE_ORDER_INT = 206;

	const SUBMIT_NEW_OCO_ORDER = 201;
	const SUBMIT_NEW_OCO_ORDER_INT = 207;

	const CANCEL_ORDER = 203;

	const CANCEL_REPLACE_ORDER = 204;
	const CANCEL_REPLACE_ORDER_INT = 205;

	// Trading related
	const OPEN_ORDERS_REQUEST = 300;
	const OPEN_ORDERS_REJECT = 302;

	const ORDER_UPDATE = 301;

	const HISTORICAL_ORDER_FILLS_REQUEST = 303;
	const HISTORICAL_ORDER_FILLS_REJECT = 308;
	const HISTORICAL_ORDER_FILL_RESPONSE = 304;

	const CURRENT_POSITIONS_REQUEST = 305;
	const CURRENT_POSITIONS_REJECT = 307;

	const POSITION_UPDATE = 306;

	// Account list
	const TRADE_ACCOUNTS_REQUEST = 400;
	const TRADE_ACCOUNT_RESPONSE = 401;

	// Symbol discovery and security definitions
	const EXCHANGE_LIST_REQUEST = 500;
	const EXCHANGE_LIST_RESPONSE = 501;

	const SYMBOLS_FOR_EXCHANGE_REQUEST = 502;
	const UNDERLYING_SYMBOLS_FOR_EXCHANGE_REQUEST = 503;
	const SYMBOLS_FOR_UNDERLYING_REQUEST = 504;
	const SECURITY_DEFINITION_FOR_SYMBOL_REQUEST = 506;
	const SECURITY_DEFINITION_RESPONSE = 507;

	const SYMBOL_SEARCH_REQUEST = 508;

	const SECURITY_DEFINITION_REJECT = 509;

	// Account balance
	const ACCOUNT_BALANCE_REQUEST = 601;
	const ACCOUNT_BALANCE_REJECT = 602;	
	const ACCOUNT_BALANCE_UPDATE = 600;

	// Logging
	const USER_MESSAGE = 700;
	const GENERAL_LOG_MESSAGE = 701;

	// Historical price data
	const HISTORICAL_PRICE_DATA_REQUEST= 800;
	const HISTORICAL_PRICE_DATA_RESPONSE_HEADER = 801;
	const HISTORICAL_PRICE_DATA_REJECT = 802;
	const HISTORICAL_PRICE_DATA_RECORD_RESPONSE = 803;
	const HISTORICAL_PRICE_DATA_TICK_RECORD_RESPONSE = 804;
	const HISTORICAL_PRICE_DATA_RECORD_RESPONSE_INT = 805;
	const HISTORICAL_PRICE_DATA_TICK_RECORD_RESPONSE_INT = 806;
	const HISTORICAL_PRICE_DATA_RESPONSE_TRAILER = 807;
